"""Interactive setup wizard for Inkwell integrations.

Walks through configuring Google (Docs + Drive), Exa, Claude cookie,
and FRED API key. Writes secrets to .env.local and handles the Google
OAuth browser flow.

Usage::

    $ uv run lup-devtools setup          # Full walkthrough
    $ uv run lup-devtools setup google   # Just Google OAuth
    $ uv run lup-devtools setup status   # Show what's configured
"""

import os
import shutil
import webbrowser
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Annotated

import typer
from dotenv import dotenv_values
from oauthlib.oauth2.rfc6749.errors import AccessDeniedError
from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from lup.devtools.setup import clear_env_file
from lup.types import EnvVars

from inkwell.agent.client import PROVIDER_LOGIN, RUNTIME
from inkwell.agent.config import PROFILES_DIR, active_profile, select_profile

app = typer.Typer(
    help="Interactive setup wizard",
    pretty_exceptions_show_locals=False,
    invoke_without_command=True,
)

console = Console()

PROJECT_ROOT = Path(__file__).resolve().parents[3]
ENV_LOCAL = PROJECT_ROOT / ".env.local"
CREDENTIALS_DIR = PROJECT_ROOT / "credentials"
GOOGLE_CREDS_PATH = CREDENTIALS_DIR / "google.json"
GOOGLE_TOKEN_PATH = CREDENTIALS_DIR / "token.json"
CLAUDE_CONFIG_SUBDIR = "claude-config"


# =====================================================================
# Profile helpers
# =====================================================================


def resolve_profile() -> str | None:
    """Return the active profile name, as the agent's configuration resolves it."""
    return active_profile()


def env_file_for_profile(profile: str | None = None) -> Path:
    if profile:
        return PROFILES_DIR / profile / "env"
    return ENV_LOCAL


def credentials_dir_for_profile(profile: str | None = None) -> Path:
    if profile:
        return PROFILES_DIR / profile / "credentials"
    return CREDENTIALS_DIR


class GooglePaths(BaseModel):
    """Where a profile keeps its Google OAuth client, and the token it earned."""

    credentials: Path = Field(description="The OAuth client the user downloaded")
    token: Path = Field(description="The token the browser flow wrote back")


def google_paths_for_profile(profile: str | None = None) -> GooglePaths:
    creds_dir = credentials_dir_for_profile(profile)
    return GooglePaths(
        credentials=creds_dir / "google.json", token=creds_dir / "token.json"
    )


def claude_config_dir_for_profile(profile: str | None = None) -> Path:
    if profile:
        return PROFILES_DIR / profile / CLAUDE_CONFIG_SUBDIR
    return CREDENTIALS_DIR / CLAUDE_CONFIG_SUBDIR


def list_profiles() -> list[str]:
    """Return sorted list of profile names that have an env file."""
    if not PROFILES_DIR.exists():
        return []
    return sorted(
        p.name for p in PROFILES_DIR.iterdir() if p.is_dir() and (p / "env").exists()
    )


# =====================================================================
# .env.local / profile env helpers
# =====================================================================


def read_env_file(path: Path) -> EnvVars:
    """Parse an env file into a dict. Returns empty dict if file missing.

    Through dotenv, which is the parser pydantic-settings itself reads these
    files with — so what the wizard reports as configured is what a run will
    actually load, quoting and continuations included.
    """
    if not path.exists():
        return {}
    return {key: value for key, value in dotenv_values(path).items() if value}


def env_value(env: EnvVars, key: str) -> str:
    """The value an env file carries for `key`, or empty where it carries none.

    An env file holds whatever keys someone put in it, so a miss is ordinary
    and every caller here treats absent and blank the same way.
    """
    return env[key] if key in env else ""


def overwrite_env_file(path: Path, values: EnvVars) -> None:
    """Write values as the entire env file, replacing whatever was there."""
    lines = ["# Auto-generated by lup-devtools setup", ""]
    for key, value in sorted(values.items()):
        if ";" in value:
            lines.append(f"{key}='{value}'")
        else:
            lines.append(f"{key}={value}")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def write_env_file(path: Path, values: EnvVars) -> None:
    """Write values to an env file, preserving existing entries."""
    existing = read_env_file(path)
    existing.update(values)
    overwrite_env_file(path, existing)


def read_env_local(profile: str | None = None) -> EnvVars:
    """Parse the active profile's env file into a dict."""
    return read_env_file(env_file_for_profile(profile or resolve_profile()))


def write_env_local(values: EnvVars, profile: str | None = None) -> None:
    """Write values to the active profile's env file."""
    write_env_file(
        env_file_for_profile(profile or resolve_profile()),
        values,
    )


def clear_env_local(keys: Iterable[str], profile: str | None = None) -> None:
    """Drop keys from the active profile's env file."""
    clear_env_file(env_file_for_profile(profile or resolve_profile()), keys)


# Env keys each integration owns, keyed by the stable id the dashboard sends.
# Resetting an integration drops exactly these; those that also own files clear
# them in reset_integration below.
RESETTABLE_ENV_KEYS: dict[str, tuple[str, ...]] = {
    "google": ("GOOGLE_CREDENTIALS_PATH", "GOOGLE_TOKEN_PATH"),
    "session": ("CLAUDE_COOKIE", "CLAUDE_ORG_UUID"),
    "author": ("INKWELL_AUTHOR_EMAIL",),
    "exa": ("EXA_API_KEY",),
    "fred": ("FRED_API_KEY",),
    "claude-login": (PROVIDER_LOGIN.config_home_env,),
}


def reset_integration(integration: str, profile: str | None = None) -> None:
    """Erase everything one integration configured for a profile.

    The inverse of authorizing it: drop the integration's env keys and delete any
    on-disk artifacts it owns — Google's OAuth client and token, the claude.ai
    durable browser session — so it reads "not configured" and can be redone from
    scratch, without deleting the whole profile. Raises ``KeyError`` for an
    unknown integration id.
    """
    clear_env_local(RESETTABLE_ENV_KEYS[integration], profile)
    match integration:
        case "google":
            paths = google_paths_for_profile(profile)
            paths.credentials.unlink(missing_ok=True)
            paths.token.unlink(missing_ok=True)
        case "session":
            from inkwell.agent.browser_auth import clear_context

            clear_context(profile)


def save_and_confirm(values: EnvVars) -> None:
    """Write values to the active env file and print confirmation."""
    if values:
        profile = resolve_profile()
        write_env_local(values, profile)
        target = env_file_for_profile(profile)
        console.print(f"[green]Saved to {target.relative_to(PROJECT_ROOT)}[/]")


def mask(value: str, show: int = 6) -> str:
    """Mask a secret string, showing only the first few characters."""
    if len(value) <= show:
        return value
    return value[:show] + "..." + "*" * min(8, len(value) - show)


class GraphicalSession(BaseSettings):
    """Whether the host advertises a display server a browser could open on."""

    model_config = SettingsConfigDict(extra="ignore")

    display: str = Field(default="", validation_alias="DISPLAY")
    wayland_display: str = Field(default="", validation_alias="WAYLAND_DISPLAY")


def has_graphical_display() -> bool:
    """Check whether a graphical browser is likely available."""
    session = GraphicalSession()
    if session.display or session.wayland_display:
        return True
    if shutil.which("open") and os.uname().sysname == "Darwin":
        return True
    return False


def open_browser(url: str) -> None:
    """Open a URL in the default browser, with fallback message.

    Skips webbrowser.open() when no graphical display is detected to
    avoid launching terminal browsers (elinks, lynx) that block the
    process.
    """
    console.print(f"  Opening [link={url}]{url}[/link]")
    if not has_graphical_display():
        console.print(f"  [dim]No graphical display — go to: {url}[/dim]")
        return
    try:
        webbrowser.open(url)
    except OSError:
        console.print(f"  [dim]Could not open browser. Go to: {url}[/dim]")


def print_test_user_guidance() -> None:
    """Print instructions for adding a test user to the Google Cloud project."""
    console.print(
        "[red]OAuth flow failed:[/] access denied\n"
        "\n"
        "  Your Google Cloud project is in [bold]testing[/] mode and the\n"
        "  account you signed in with isn't listed as a test user.\n"
        "  (This can be a different account than the project owner.)\n"
        "\n"
        "  [bold]To fix:[/]\n"
        "  1. Go to [link=https://console.cloud.google.com/auth/audience]"
        "Google Cloud → OAuth consent → Audience[/link]\n"
        "  2. Under [bold]Test users[/], click [bold]+ Add users[/]\n"
        "  3. Enter the email you're authorizing with and save\n"
        "  4. Retry: [bold]uv run lup-devtools setup google[/]\n"
    )
    open_browser("https://console.cloud.google.com/auth/audience")


# =====================================================================
# Status display
# =====================================================================


def build_status_table(profile: str | None = None) -> Table:
    """Build a rich table showing configuration status."""
    profile = profile or resolve_profile()
    env = read_env_local(profile)
    google = google_paths_for_profile(profile)
    google_creds, google_token = google.credentials, google.token

    title = f"Profile: [bold]{profile}[/]" if profile else "Default configuration"
    table = Table(title=title, show_header=False, box=None, padding=(0, 2))
    table.add_column("Status", width=3)
    table.add_column("Integration", min_width=30)
    table.add_column("Detail", style="dim")

    config_dir = env_value(env, PROVIDER_LOGIN.config_home_env)
    login_ok = bool(config_dir) and PROVIDER_LOGIN.logged_in(Path(config_dir))
    table.add_row(
        "[green]OK[/]" if login_ok else "[dim]--[/]",
        f"{RUNTIME.name} login",
        config_dir if login_ok else f"using default (shared with {RUNTIME.name})",
    )

    google_ok = google_token.exists()
    google_creds_ok = google_creds.exists()
    if google_ok:
        detail = "authorized"
    elif google_creds_ok:
        detail = "credentials present, not yet authorized"
    else:
        detail = "not configured"
    table.add_row(
        "[green]OK[/]" if google_ok else "[red]--[/]",
        "Google (Docs + Drive)",
        detail,
    )

    exa_ok = bool(env_value(env, "EXA_API_KEY"))
    table.add_row(
        "[green]OK[/]" if exa_ok else "[red]--[/]",
        "Exa",
        mask(env["EXA_API_KEY"]) if exa_ok else "not configured",
    )

    import asyncio

    from inkwell.agent.browser_auth import context_has_cookies

    has_browser = asyncio.run(context_has_cookies(profile))
    has_cookie = bool(env_value(env, "CLAUDE_COOKIE"))
    claude_ok = has_browser or has_cookie
    if has_browser:
        claude_detail = "browser session stored"
    elif has_cookie:
        claude_detail = f"cookie: {mask(env['CLAUDE_COOKIE'])}"
    else:
        claude_detail = "not configured"
    table.add_row(
        "[green]OK[/]" if claude_ok else "[dim]--[/]",
        "Claude.ai session",
        claude_detail,
    )

    fred_ok = bool(env_value(env, "FRED_API_KEY"))
    table.add_row(
        "[green]OK[/]" if fred_ok else "[dim]--[/]",
        "FRED",
        mask(env["FRED_API_KEY"]) if fred_ok else "not configured (optional)",
    )

    return table


@app.command("status")
def status() -> None:
    """Show current integration status."""
    console.print()
    console.print(build_status_table())
    console.print()


# =====================================================================
# Google
# =====================================================================


def place_google_credentials(target_dir: Path, target_path: Path) -> None:
    """Prompt user for credentials JSON path and copy to target."""
    source = typer.prompt(
        "Path to downloaded credentials JSON",
    ).strip()
    source_path = Path(source).expanduser().resolve()

    if not source_path.exists():
        console.print(f"[red]File not found:[/] {source_path}")
        raise typer.Abort()

    target_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, target_path)
    console.print(f"  Copied to [bold]{target_path}[/]")


def setup_google() -> EnvVars:
    """Walk through Google OAuth setup step by step. Returns env vars to set."""
    profile = resolve_profile()
    google = google_paths_for_profile(profile)
    creds_path, token_path = google.credentials, google.token

    console.print()
    console.rule("[bold]Google (Docs + Drive)[/]")
    console.print()

    if token_path.exists():
        console.print("[green]Already authorized.[/]")
        if not typer.confirm("Re-authorize?", default=False):
            return {
                "GOOGLE_CREDENTIALS_PATH": str(creds_path),
                "GOOGLE_TOKEN_PATH": str(token_path),
            }

    if not creds_path.exists():
        console.print("  [bold]Step 1:[/] Create a Google Cloud project\n")
        open_browser("https://console.cloud.google.com/projectcreate")
        typer.prompt(
            "  Press Enter when your project is created", default="", show_default=False
        )

        console.print("\n  [bold]Step 2:[/] Enable Google Docs API")
        open_browser(
            "https://console.cloud.google.com/apis/library/docs.googleapis.com"
        )
        typer.prompt("  Press Enter after enabling", default="", show_default=False)

        console.print("\n  [bold]Step 3:[/] Enable Google Drive API")
        open_browser(
            "https://console.cloud.google.com/apis/library/drive.googleapis.com"
        )
        typer.prompt("  Press Enter after enabling", default="", show_default=False)

        console.print(
            "\n  [bold]Step 4a:[/] Configure OAuth consent screen\n"
            "  [dim]Select External > Create, fill in app name + your email, skip scopes.[/]"
        )
        open_browser("https://console.cloud.google.com/apis/credentials/consent")
        typer.prompt(
            "  Press Enter when consent screen is created",
            default="",
            show_default=False,
        )

        console.print(
            "\n  [bold]Step 4b:[/] Add a test user\n"
            "  [bold yellow]Important:[/] Click [bold]+ Add users[/] and enter the Google email\n"
            "  you'll authorize with. This can be a different account than the\n"
            "  project owner — add whichever email you'll sign in with next.\n"
            "  Without this, the OAuth flow will fail with [dim]Error 403: access_denied[/]."
        )
        open_browser("https://console.cloud.google.com/auth/audience")
        typer.prompt(
            "  Press Enter when the email is added as a test user",
            default="",
            show_default=False,
        )

        console.print(
            "\n  [bold]Step 5:[/] Create OAuth client ID\n"
            '  [dim]Click "Create Credentials" > OAuth client ID > Desktop app > Create\n'
            "  Then download the JSON file[/]"
        )
        open_browser("https://console.cloud.google.com/apis/credentials")
        console.print()
        place_google_credentials(creds_path.parent, creds_path)
    else:
        console.print(f"  Using existing credentials at [bold]{creds_path}[/]")
        console.print(
            '\n  [bold yellow]Note:[/] If you see [dim]"app not verified"[/] or [dim]"access denied"[/],\n'
            "  make sure the account you're signing in with is listed as a test user\n"
            "  on the project (this can differ from the project owner):\n"
            "  https://console.cloud.google.com/auth/audience\n"
        )

    console.print(
        "  [bold]Authorizing...[/] Grant access to Google Docs and Drive in the browser."
    )
    console.print()

    try:
        from inkwell.agent.google_auth import run_oauth_flow

        run_oauth_flow(str(creds_path), str(token_path))
        console.print(f"[green]Google authorized![/] Token saved to {token_path}")
    except FileNotFoundError as e:
        console.print(f"[red]Error:[/] {e}")
        return {}
    except AccessDeniedError:
        print_test_user_guidance()
        return {}
    except RuntimeError as e:
        error_msg = str(e).lower()
        if "access_denied" in error_msg or "verification" in error_msg:
            print_test_user_guidance()
        else:
            console.print(f"[red]OAuth flow failed:[/] {e}")
            console.print("Retry with: [bold]uv run lup-devtools setup google[/]")
        return {}

    return {
        "GOOGLE_CREDENTIALS_PATH": str(creds_path),
        "GOOGLE_TOKEN_PATH": str(token_path),
    }


# =====================================================================
# Exa
# =====================================================================


def setup_exa() -> EnvVars:
    """Walk through Exa configuration. Returns env vars to set."""
    console.print()
    console.rule("[bold]Exa[/]")
    console.print()

    env = read_env_local()

    if env_value(env, "EXA_API_KEY"):
        console.print("[green]Already configured.[/]")
        if not typer.confirm("Reconfigure?", default=False):
            return {}

    console.print("  AI-powered web search for research.\n")
    open_browser("https://dashboard.exa.ai/api-keys")
    console.print()

    key = typer.prompt(
        "EXA_API_KEY",
        default=env_value(env, "EXA_API_KEY"),
        show_default=False,
    ).strip()

    if key:
        return {"EXA_API_KEY": key}
    return {}


# =====================================================================
# Claude cookie
# =====================================================================


def setup_claude() -> EnvVars:
    """Walk through Claude.ai session setup via managed browser. Returns env vars to set."""
    import asyncio

    from inkwell.agent.browser_auth import context_has_cookies, login_interactive

    profile = resolve_profile()

    console.print()
    console.rule("[bold]Claude.ai session[/]")
    console.print()

    if asyncio.run(context_has_cookies(profile)):
        console.print("[green]Browser session already stored.[/]")
        if not typer.confirm("Re-login?", default=False):
            return {}

    console.print(
        "  Used to extract conversations from Claude share links.\n"
        "  A dedicated browser window will open — log in to claude.ai.\n"
        "  [dim]This session is stored separately from your main browser,[/]\n"
        "  [dim]so logging out of Chrome won't affect extraction.[/]\n"
    )

    if not has_graphical_display():
        cmd = "inkwell setup claude"
        if profile:
            cmd += f" --profile {profile}"
        console.print(
            "  [yellow]No graphical display detected.[/]\n"
            "  Run this in your terminal to log in with a browser:\n"
            f"\n"
            f"    [bold]! {cmd}[/]\n"
            f"\n"
            "  Or paste a cookie manually:\n"
        )
        cookie = typer.prompt(
            "CLAUDE_COOKIE (or press Enter to skip)",
            default="",
            show_default=False,
        ).strip()
        if cookie:
            return {"CLAUDE_COOKIE": cookie}
        return {}

    if not typer.confirm("Open browser to log in?", default=True):
        return {}

    logged_in = asyncio.run(login_interactive(profile))
    if logged_in:
        console.print("[green]Login successful — session saved.[/]")
    else:
        console.print("[yellow]Login may not have completed.[/]")
        console.print("  Retry with: [bold]uv run lup-devtools setup claude[/]")

    return {}


# =====================================================================
# FRED
# =====================================================================


def setup_fred() -> EnvVars:
    """Walk through FRED API key setup. Returns env vars to set."""
    console.print()
    console.rule("[bold]FRED[/] [dim](optional)[/]")
    console.print()

    env = read_env_local()

    if env_value(env, "FRED_API_KEY"):
        console.print("[green]Already configured.[/]")
        if not typer.confirm("Reconfigure?", default=False):
            return {}

    console.print(
        "  Federal Reserve Economic Data — used for economic research.\n"
        "  [dim]Free API key, only needed for economics-related articles.[/]\n"
    )
    open_browser("https://fred.stlouisfed.org/docs/api/api_key.html")
    console.print()

    key = typer.prompt(
        "FRED_API_KEY (or press Enter to skip)",
        default=env_value(env, "FRED_API_KEY"),
        show_default=False,
    ).strip()

    if key:
        return {"FRED_API_KEY": key}
    return {}


# =====================================================================
# Claude login (separate account for the writing agent)
# =====================================================================


def setup_claude_login() -> EnvVars:
    """Set up a separate Claude login for the writing agent."""
    import sh

    profile = resolve_profile()
    config_dir = claude_config_dir_for_profile(profile)

    console.print()
    console.rule("[bold]Claude login[/]")
    console.print()

    env = read_env_local(profile)
    existing_dir = env_value(env, PROVIDER_LOGIN.config_home_env)

    if existing_dir and Path(existing_dir).exists():
        if PROVIDER_LOGIN.logged_in(Path(existing_dir)):
            console.print(
                f"[green]Already configured.[/] Using [bold]{existing_dir}[/]"
            )
            if not typer.confirm("Re-login?", default=False):
                return {}

    console.print(
        "  Inkwell's writing agent uses Claude Code under the hood.\n"
        "  By default it shares your current Claude Code login.\n"
        "\n"
        "  You can log in with a separate account so the agent's\n"
        "  usage is billed separately from your dev session.\n"
    )

    if not typer.confirm("Set up a separate login?", default=bool(existing_dir)):
        return {}

    config_dir.mkdir(parents=True, exist_ok=True)

    console.print(
        f"\n  Logging in with config dir: [bold]{config_dir}[/]\n"
        "  A browser window will open — sign in with the account\n"
        "  you want the writing agent to use.\n"
    )

    login_env = {
        **os.environ,  # lup: ignore[os-environ] — exact child-process inheritance
        **PROVIDER_LOGIN.environment(config_dir),
    }
    claude = sh.Command("claude")
    try:
        claude("/login", _env=login_env, _fg=True)
    except sh.ErrorReturnCode:
        console.print(
            "[red]Login failed.[/] Retry with: [bold]uv run lup-devtools setup claude-login[/]"
        )
        return {}

    console.print("[green]Logged in![/]")
    return PROVIDER_LOGIN.environment(config_dir)


# =====================================================================
# Integration registry
# =====================================================================

type SetupFunc = Callable[[], EnvVars]

INTEGRATION_FUNCS: list[SetupFunc] = [
    setup_claude_login,
    setup_google,
    setup_exa,
    setup_claude,
    setup_fred,
]


# =====================================================================
# Individual subcommands
# =====================================================================


@app.command("claude-login")
def claude_login_cmd(
    profile: Annotated[
        str | None,
        typer.Option(
            "--profile", "-p", help="Configuration profile", envvar="INKWELL_PROFILE"
        ),
    ] = None,
) -> None:
    """Set up a separate Claude login for the writing agent."""
    if profile:
        select_profile(profile)
    save_and_confirm(setup_claude_login())


@app.command("google")
def google_cmd(
    profile: Annotated[
        str | None,
        typer.Option(
            "--profile", "-p", help="Configuration profile", envvar="INKWELL_PROFILE"
        ),
    ] = None,
) -> None:
    """Set up Google (Docs + Drive) OAuth."""
    if profile:
        select_profile(profile)
    save_and_confirm(setup_google())


@app.command("exa")
def exa_cmd(
    profile: Annotated[
        str | None,
        typer.Option(
            "--profile", "-p", help="Configuration profile", envvar="INKWELL_PROFILE"
        ),
    ] = None,
) -> None:
    """Set up Exa API key."""
    if profile:
        select_profile(profile)
    save_and_confirm(setup_exa())


@app.command("claude")
def claude_cmd(
    profile: Annotated[
        str | None,
        typer.Option(
            "--profile", "-p", help="Configuration profile", envvar="INKWELL_PROFILE"
        ),
    ] = None,
) -> None:
    """Set up Claude.ai session for conversation extraction."""
    if profile:
        select_profile(profile)
    save_and_confirm(setup_claude())


@app.command("fred")
def fred_cmd(
    profile: Annotated[
        str | None,
        typer.Option(
            "--profile", "-p", help="Configuration profile", envvar="INKWELL_PROFILE"
        ),
    ] = None,
) -> None:
    """Set up FRED API key."""
    if profile:
        select_profile(profile)
    save_and_confirm(setup_fred())


# =====================================================================
# Full wizard (default command)
# =====================================================================

# NOTE: Register this app in src/inkwell/devtools/main.py:
#   from inkwell.devtools.setup import app as setup_app
#   app.add_typer(setup_app, name="setup", help="Interactive setup wizard")


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    profile: Annotated[
        str | None,
        typer.Option(
            "--profile",
            "-p",
            help="Configuration profile to set up",
            envvar="INKWELL_PROFILE",
        ),
    ] = None,
) -> None:
    """Walk through all integrations, skipping what's already configured."""
    if profile:
        select_profile(profile)
    if ctx.invoked_subcommand is not None:
        return

    active = resolve_profile()
    label = f"profile [bold]{active}[/]" if active else "default configuration"

    console.print()
    console.print(
        Panel(
            f"[bold]Inkwell setup[/] ({label})\n"
            "\n"
            "Walking through all integrations.\n"
            "Press [bold]Ctrl+C[/] to exit, [bold]Enter[/] to skip a field.",
            expand=False,
        )
    )

    console.print(build_status_table())

    for func in INTEGRATION_FUNCS:
        values = func()
        if values:
            write_env_local(values)

    console.print()
    console.rule("[bold green]Setup complete[/]")
    console.print()
    console.print(build_status_table())
    console.print()
