"""Interactive setup wizard for Inkwell integrations.

Walks through configuring Google (Docs + Drive), Exa, Claude cookie,
and FRED API key. Writes secrets to .env.local and handles the Google
OAuth browser flow.

Usage::

    $ uv run lup-devtools setup          # Full walkthrough
    $ uv run lup-devtools setup google   # Just Google OAuth
    $ uv run lup-devtools setup status   # Show what's configured
"""

from __future__ import annotations

import shutil
import webbrowser
from collections.abc import Callable
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

app = typer.Typer(
    help="Interactive setup wizard",
    pretty_exceptions_show_locals=False,
    invoke_without_command=True,
)

console = Console()

PROJECT_ROOT = Path(__file__).resolve().parents[3]
ENV_LOCAL = PROJECT_ROOT / ".env.local"
CREDENTIALS_DIR = PROJECT_ROOT / "credentials"
GOOGLE_CREDS_PATH = CREDENTIALS_DIR / "google.json"
GOOGLE_TOKEN_PATH = CREDENTIALS_DIR / "token.json"


# =====================================================================
# .env.local helpers
# =====================================================================


def read_env_local() -> dict[str, str]:
    """Parse .env.local into a dict. Returns empty dict if file missing."""
    if not ENV_LOCAL.exists():
        return {}
    values: dict[str, str] = {}
    for line in ENV_LOCAL.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def write_env_local(values: dict[str, str]) -> None:
    """Write values to .env.local, preserving existing entries."""
    existing = read_env_local()
    existing.update(values)

    lines = ["# Auto-generated by lup-devtools setup", ""]
    for key, value in sorted(existing.items()):
        lines.append(f"{key}={value}")
    lines.append("")

    ENV_LOCAL.write_text("\n".join(lines))


def save_and_confirm(values: dict[str, str]) -> None:
    """Write values to .env.local and print confirmation."""
    if values:
        write_env_local(values)
        console.print("[green]Saved to .env.local[/]")


def mask(value: str, show: int = 6) -> str:
    """Mask a secret string, showing only the first few characters."""
    if len(value) <= show:
        return value
    return value[:show] + "..." + "*" * min(8, len(value) - show)


def open_browser(url: str) -> None:
    """Open a URL in the default browser, with fallback message."""
    console.print(f"  Opening [link={url}]{url}[/link]")
    try:
        webbrowser.open(url)
    except OSError:
        console.print(f"  [dim]Could not open browser. Go to: {url}[/dim]")


# =====================================================================
# Status display
# =====================================================================


def build_status_table() -> Table:
    """Build a rich table showing configuration status."""
    env = read_env_local()

    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column("Status", width=3)
    table.add_column("Integration", min_width=30)
    table.add_column("Detail", style="dim")

    google_ok = GOOGLE_TOKEN_PATH.exists()
    google_creds_ok = GOOGLE_CREDS_PATH.exists()
    if google_ok:
        detail = "authorized"
    elif google_creds_ok:
        detail = "credentials present, not yet authorized"
    else:
        detail = "not configured"
    table.add_row(
        "[green]OK[/]" if google_ok else "[red]--[/]",
        "Google (Docs + Drive)",
        detail,
    )

    exa_ok = bool(env.get("EXA_API_KEY"))
    table.add_row(
        "[green]OK[/]" if exa_ok else "[red]--[/]",
        "Exa",
        mask(env["EXA_API_KEY"]) if exa_ok else "not configured",
    )

    claude_ok = bool(env.get("CLAUDE_COOKIE"))
    table.add_row(
        "[green]OK[/]" if claude_ok else "[dim]--[/]",
        "Claude cookie",
        mask(env["CLAUDE_COOKIE"]) if claude_ok else "not configured (optional)",
    )

    fred_ok = bool(env.get("FRED_API_KEY"))
    table.add_row(
        "[green]OK[/]" if fred_ok else "[dim]--[/]",
        "FRED",
        mask(env["FRED_API_KEY"]) if fred_ok else "not configured (optional)",
    )

    return table


@app.command("status")
def status() -> None:
    """Show current integration status."""
    console.print()
    console.print(build_status_table())
    console.print()


# =====================================================================
# Google
# =====================================================================


def place_google_credentials() -> None:
    """Prompt user for credentials JSON path and copy to credentials/."""
    source = typer.prompt(
        "Path to downloaded credentials JSON",
    ).strip()
    source_path = Path(source).expanduser().resolve()

    if not source_path.exists():
        console.print(f"[red]File not found:[/] {source_path}")
        raise typer.Abort()

    CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, GOOGLE_CREDS_PATH)
    console.print(f"  Copied to [bold]{GOOGLE_CREDS_PATH}[/]")


def setup_google() -> dict[str, str]:
    """Walk through Google OAuth setup step by step. Returns env vars to set."""
    console.print()
    console.rule("[bold]Google (Docs + Drive)[/]")
    console.print()

    if GOOGLE_TOKEN_PATH.exists():
        console.print("[green]Already authorized.[/]")
        if not typer.confirm("Re-authorize?", default=False):
            return {
                "GOOGLE_CREDENTIALS_PATH": str(GOOGLE_CREDS_PATH),
                "GOOGLE_TOKEN_PATH": str(GOOGLE_TOKEN_PATH),
            }

    if not GOOGLE_CREDS_PATH.exists():
        console.print("  [bold]Step 1:[/] Create a Google Cloud project\n")
        open_browser("https://console.cloud.google.com/projectcreate")
        typer.prompt(
            "  Press Enter when your project is created", default="", show_default=False
        )

        console.print("\n  [bold]Step 2:[/] Enable Google Docs API")
        open_browser(
            "https://console.cloud.google.com/apis/library/docs.googleapis.com"
        )
        typer.prompt("  Press Enter after enabling", default="", show_default=False)

        console.print("\n  [bold]Step 3:[/] Enable Google Drive API")
        open_browser(
            "https://console.cloud.google.com/apis/library/drive.googleapis.com"
        )
        typer.prompt("  Press Enter after enabling", default="", show_default=False)

        console.print(
            "\n  [bold]Step 4a:[/] Configure OAuth consent screen\n"
            "  [dim]Select External > Create, fill in app name + your email, skip scopes.[/]"
        )
        open_browser("https://console.cloud.google.com/apis/credentials/consent")
        typer.prompt(
            "  Press Enter when consent screen is created",
            default="",
            show_default=False,
        )

        console.print(
            "\n  [bold]Step 4b:[/] Add yourself as a test user\n"
            "  [bold yellow]Important:[/] Click [bold]+ Add users[/] and enter your Google email.\n"
            "  Without this, the OAuth flow will fail with [dim]Error 403: access_denied[/]."
        )
        open_browser("https://console.cloud.google.com/auth/audience")
        typer.prompt(
            "  Press Enter when your email is added as a test user",
            default="",
            show_default=False,
        )

        console.print(
            "\n  [bold]Step 5:[/] Create OAuth client ID\n"
            '  [dim]Click "Create Credentials" > OAuth client ID > Desktop app > Create\n'
            "  Then download the JSON file[/]"
        )
        open_browser("https://console.cloud.google.com/apis/credentials")
        console.print()
        place_google_credentials()
    else:
        console.print(f"  Using existing credentials at [bold]{GOOGLE_CREDS_PATH}[/]")

    console.print()
    console.print(
        "  [bold]Authorizing...[/] Grant access to Google Docs and Drive in the browser."
    )
    console.print()

    try:
        from inkwell.agent.google_auth import run_oauth_flow

        run_oauth_flow(str(GOOGLE_CREDS_PATH), str(GOOGLE_TOKEN_PATH))
        console.print(
            "[green]Google authorized![/] Token saved to credentials/token.json"
        )
    except FileNotFoundError as e:
        console.print(f"[red]Error:[/] {e}")
        return {}
    except RuntimeError as e:
        console.print(f"[red]OAuth flow failed:[/] {e}")
        console.print("Retry with: [bold]uv run lup-devtools setup google[/]")
        return {}

    return {
        "GOOGLE_CREDENTIALS_PATH": str(GOOGLE_CREDS_PATH),
        "GOOGLE_TOKEN_PATH": str(GOOGLE_TOKEN_PATH),
    }


# =====================================================================
# Exa
# =====================================================================


def setup_exa() -> dict[str, str]:
    """Walk through Exa configuration. Returns env vars to set."""
    console.print()
    console.rule("[bold]Exa[/]")
    console.print()

    env = read_env_local()

    if env.get("EXA_API_KEY"):
        console.print("[green]Already configured.[/]")
        if not typer.confirm("Reconfigure?", default=False):
            return {}

    console.print("  AI-powered web search for research.\n")
    open_browser("https://dashboard.exa.ai/api-keys")
    console.print()

    key = typer.prompt(
        "EXA_API_KEY",
        default=env.get("EXA_API_KEY", ""),
        show_default=False,
    ).strip()

    if key:
        return {"EXA_API_KEY": key}
    return {}


# =====================================================================
# Claude cookie
# =====================================================================


def setup_claude() -> dict[str, str]:
    """Walk through Claude cookie setup. Returns env vars to set."""
    console.print()
    console.rule("[bold]Claude cookie[/] [dim](optional)[/]")
    console.print()

    env = read_env_local()

    if env.get("CLAUDE_COOKIE"):
        console.print("[green]Already configured.[/]")
        if not typer.confirm("Reconfigure?", default=False):
            return {}

    console.print(
        "  Used to extract conversations from Claude share links.\n"
        "  [dim]Without this, share link extraction is disabled.[/]\n"
    )
    console.print(
        "  To get your cookie:\n"
        "  1. Open claude.ai in your browser, sign in\n"
        "  2. Open DevTools (F12) > Application > Cookies > https://claude.ai\n"
        '  3. Copy the value of the cookie named [bold]sessionKey[/] (starts with "sk-ant-")\n'
    )
    open_browser("https://claude.ai")
    console.print()

    cookie = typer.prompt(
        "CLAUDE_COOKIE (or press Enter to skip)",
        default=env.get("CLAUDE_COOKIE", ""),
        show_default=False,
    ).strip()

    if cookie:
        return {"CLAUDE_COOKIE": cookie}
    return {}


# =====================================================================
# FRED
# =====================================================================


def setup_fred() -> dict[str, str]:
    """Walk through FRED API key setup. Returns env vars to set."""
    console.print()
    console.rule("[bold]FRED[/] [dim](optional)[/]")
    console.print()

    env = read_env_local()

    if env.get("FRED_API_KEY"):
        console.print("[green]Already configured.[/]")
        if not typer.confirm("Reconfigure?", default=False):
            return {}

    console.print(
        "  Federal Reserve Economic Data — used for economic research.\n"
        "  [dim]Free API key, only needed for economics-related articles.[/]\n"
    )
    open_browser("https://fred.stlouisfed.org/docs/api/api_key.html")
    console.print()

    key = typer.prompt(
        "FRED_API_KEY (or press Enter to skip)",
        default=env.get("FRED_API_KEY", ""),
        show_default=False,
    ).strip()

    if key:
        return {"FRED_API_KEY": key}
    return {}


# =====================================================================
# Integration registry
# =====================================================================

type SetupFunc = Callable[[], dict[str, str]]

INTEGRATION_FUNCS: list[SetupFunc] = [
    setup_google,
    setup_exa,
    setup_claude,
    setup_fred,
]


# =====================================================================
# Individual subcommands
# =====================================================================


@app.command("google")
def google_cmd() -> None:
    """Set up Google (Docs + Drive) OAuth."""
    save_and_confirm(setup_google())


@app.command("exa")
def exa_cmd() -> None:
    """Set up Exa API key."""
    save_and_confirm(setup_exa())


@app.command("claude")
def claude_cmd() -> None:
    """Set up Claude cookie for conversation extraction."""
    save_and_confirm(setup_claude())


@app.command("fred")
def fred_cmd() -> None:
    """Set up FRED API key."""
    save_and_confirm(setup_fred())


# =====================================================================
# Full wizard (default command)
# =====================================================================

# NOTE: Register this app in src/inkwell/devtools/main.py:
#   from inkwell.devtools.setup import app as setup_app
#   app.add_typer(setup_app, name="setup", help="Interactive setup wizard")


@app.callback(invoke_without_command=True)
def main(ctx: typer.Context) -> None:
    """Walk through all integrations, skipping what's already configured."""
    if ctx.invoked_subcommand is not None:
        return

    console.print()
    console.print(
        Panel(
            "[bold]Inkwell setup[/]\n"
            "\n"
            "Walking through all integrations.\n"
            "Press [bold]Ctrl+C[/] to exit, [bold]Enter[/] to skip a field.",
            expand=False,
        )
    )

    console.print(build_status_table())

    for func in INTEGRATION_FUNCS:
        values = func()
        if values:
            write_env_local(values)

    console.print()
    console.rule("[bold green]Setup complete[/]")
    console.print()
    console.print(build_status_table())
    console.print()
