"""This application's sub-app roster: what it inherits, and what only it has.

The library ships no roster — each of its sub-apps declares itself beside its
Typer app, and a project names the ones it wants. inkwell drives Claude Code,
so it takes `usage` too; a project on another backend would compose the rest
and leave that one out.

Only the application half is specs here, never Typer apps. Documents under
``harness/content/`` describe this CLI and are themselves generated by it, so
a roster that imported those apps to learn their names would make the
guidance depend on the tooling that renders it. ``devtools/main.py`` is where
each application name meets the app that answers to it, and nothing imports
``main``. The inherited entries carry their apps already, because library
modules import nothing from this package and so close no loop.
"""

import lup.adapters.claude.usage.app as usage
import lup.devtools.py.app as py
import lup.devtools.sync as sync
import lup.devtools.trace.app as trace
import lup.devtools.version as version
from lup.devtools.subapps import SubAppSpec

INHERITED = [py.SUBAPP, sync.SUBAPP, trace.SUBAPP, usage.SUBAPP, version.SUBAPP]
"""The sub-apps inkwell takes from the library rather than writing."""

APPLICATION_SPECS = [
    SubAppSpec(name="agent", help="Agent introspection and debugging"),
    SubAppSpec(name="api", help="API inspection"),
    SubAppSpec(name="dev", help="Worktrees, branches, and pre-flight checks"),
    SubAppSpec(name="feedback", help="Feedback state, metrics, and commits"),
    SubAppSpec(name="harness", help="Generate and launch the native harness"),
    SubAppSpec(name="setup", help="Interactive setup wizard"),
]
"""The sub-apps only inkwell has, because only it has their subject."""

SUBAPP_SPECS = sorted(
    [*[entry.spec for entry in INHERITED], *APPLICATION_SPECS],
    key=lambda spec: spec.name,
)
"""Every sub-app this CLI serves, in the order `--help` lists them."""
